alias joplin="~/.joplin/Joplin.AppImage"
alias cockatrice="flatpak run io.github.Cockatrice.cockatrice"
alias slime="wine ~/Downloads/Slime.Rancher.v1.4.4/Slime.Rancher.v1.4.4/SlimeRancher.exe"
alias ls="ls -a"
alias icat="kitty +kitten icat"
alias zoom="flatpak run us.zoom.Zoom"
